export const FPS = 30;

export const TIMING = {
  A_IMAGE_REVEAL_START: 0,
  A_IMAGE_REVEAL_END: 60,
  A_FRASE_IN_START: 45,
  A_FRASE_IN_END: 90,
  A_AUTOR_IN_START: 90,
  A_AUTOR_IN_END: 114,
  A_HOLD_END: 195,
  A_FADE_OUT_END: 240,

  B_FRASE_VISIBLE_FROM: 0,
  B_AUTOR_VISIBLE_FROM: 0,
  B_HOLD_END: 195,
  B_FADE_OUT_END: 240,

  TOTAL_FRAMES: 240,
} as const;
